script:
  - "bundle exec rake neo4j:install['community-2.2.0-M02'] neo4j:start default --trace"
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email:
    recipients:
      - mikesaurio@gmail.com
before_script:
  - psql -c "CREATE USER mikesaurio WITH PASSWORD 'maikisaurio';" -U postgres