AMAZON_ACCESS_KEY: 'SOMETHING'
AMAZON_SECRET_KEY: 'SOMETHING'
S3_BUCKET: 'SOMETHING'
AMAZON_REGION: 'SOMETHING'
gmail_username: 'username@gmail.com'
gmail_password: 'Gmail password'
facebook_secret: ''
facebook_id: ''
linkedin_secret: ''
linkedin_id: ''
SMTP_CONFIG_USERNAME: 'SOMETHING'
SMTP_CONFIG_PASSWORD: 'SOMETHING'
SMTP_CONFIG_DOMAIN: 'SOMETHING'
SMTP_CONFIG_ADDRESS: 'smtp.SOMETHING'
ACTION_MAILER_HOST: 'SOMETHING'
MAILER_DEFAULT_FROM: 'something@mail.com'
USERVOICE_SUBDOMAIN_NAME: 'SOMETHING'
USERVOICE_API_KEY: 'SOMETHING'
USERVOICE_API_SECRET: 'SOMETHING'
SECRET_KEY_BASE: 'SOMETHING'