AMAZON_ACCESS_KEY: 'SOMETHING'
AMAZON_SECRET_KEY: 'SOMETHING'
S3_BUCKET: 'SOMETHING'
AMAZON_REGION: 'SOMETHING'
gmail_username: 'username@gmail.com'
gmail_password: 'Gmail password'
facebook_secret: ''
facebook_id: ''
linkedin_secret: ''
linkedin_id: ''
