name             'minegocio'
maintainer       'Mikesaurio and MA'
maintainer_email 'mikesaurio@civica.digital & miguel.angel@civica.digital'
license          'AGPL v3.0'
description      'Installs/Configures mi negocio'
version          '0.1.0'
depends          'docker', '~> 0.40.3'
depends          'git', '~> 4.3.3'